### ISSUE TITLE
metrics: paired metrics are slow

### ISSUE THREAD

**Issue by glouppe** [inveniosoftware/beard#10]
Paired scoring metrics are quite slow to compute. I think there is room for improvement. 

CC: @etzemis

**Comment by etzemis** [comment]
Ok, I will take care of those.

**Comment by glouppe** [comment]
It seems there is a linear algorithm to compute these metrics. See the last slide of http://infolab.stanford.edu/~euijong/vldb10_measure.pdf

**Comment by glouppe** [comment]
http://eggiweg.ofb.net/thesis.pdf Secyion 6.6.2

**Comment by glouppe** [comment]
And here is an implementation in R
https://github.com/hussaibi/libclustER/blob/master/trunk/src/measures.R#L277

**Comment by glouppe** [comment]
> http://eggiweg.ofb.net/thesis.pdf Section 6.6.2

This looks very pythonic. It shouldnt be too difficult to actually implement.

**Comment by glouppe** [comment]
Fixed in #14
