### ISSUE TITLE
Standalone application for disambiguation

### ISSUE THREAD

**Issue by glouppe** [inveniosoftware/beard#48]
As the code is growing, I think it is time for `examples/author_disambiguation_advanced.py` to be made as a standalone application for disambiguation. 

In my mind, beard (i.e. what lives under `beard/`) should be seen as a library of machine learning components that can be used for entity recognition -- author disambiguation being only one of the possible use cases. In parallel, `examples/` should include only small snippets of code, showing what you can using the tools we provide under `beard/`. In this setting, I think `author_disambiguation_advanced.py` is getting too complicated and would deserve to live on its own, e.g. under `examples/applications/author-disambiguation/`. In this way, I think we could clean and extend the code (e.g., decoupling distance learning from clustering, adding pair sampling, etc) in a more organized way without losing the genericity we envision for `beard/`. 

Opinions? @natsheh @MSusik

**Comment by MSusik** [comment]
:+1: I can take care of this.

**Comment by glouppe** [comment]
Great thanks

**Comment by natsheh** [comment]
:+1: That would be great. Once the moved to applications/author-disambiguation, I will add pair sampling and distance learning related code there.

**Comment by glouppe** [comment]
Done in #49 #52
