### ISSUE TITLE
results: learning curve for the distance model

### ISSUE THREAD

**Issue by MSusik** [inveniosoftware/beard#50]
![figure_1](https://cloud.githubusercontent.com/assets/6649290/8029274/30a6c4fa-0dbb-11e5-8ef5-306dbec64a8d.png)

The pairs were sampled by randomly sampling a block and then randomly sampling a pair from it.
3-fold cross validation was used.

The blocking used for the learning curve was `block_double_metaphone`. The file used is `allPairs.json` (the same as for https://github.com/inveniosoftware/beard/issues/42

**Comment by glouppe** [comment]
Closing
