### ISSUE TITLE
clustering: support of parallelism in blocking

### ISSUE THREAD

**Issue by glouppe** [inveniosoftware/beard#8]
Estimator fitting in `BlockClustering` is trivially parallel. It would be a nice thing to do add support of parallelism in there. 

This should  be done preferably using joblib (http://pythonhosted.org/joblib/).

**Comment by MSusik** [comment]
Paralelism! Yay! Assign me!

**Comment by glouppe** [comment]
In case you are taking care of this, can you wait for #9? I have made a few more changes to `BlockClustering`.

**Comment by MSusik** [comment]
Sure

**Comment by glouppe** [comment]
#9 is merged. You can move on @MSusik
